<?php
/**
 * Created by PhpStorm.
 * User: burn
 * Date: 2017/2/13
 * Time: 下午7:41
 *
 * 书盟的渠道类
 *
 */

namespace Admin\Controller;
use Think\Model;
use Think\AjaxPage;
use Think\Page;

class ChannelController extends BaseController
{
	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		
		/*if(cookie('uid') == 0 || !isset($_COOKIE['uid']))
		{
			$this->display('Admin/login');
		}*/
	}
	
	/**
	 * 绑定渠道用户id
	 */
	public function index()
	{

		$is_mobile=is_mobile();
		$this->assign('is_mobile',$is_mobile);
		
		if(cookie('permissions') == 0)
		{
			$uid = cookie('uid');	
			if(cookie(uid)<=0){
				$url = U('Admin/Admin/Login');
				
				$this->error('请先登录',$url,3);
				
				exit;
			}

			//edit by muyi 2017.05.04
            //添加渠道用户总体信息
			$where=array('uid'=>$uid);
			$channelModel=D('Channel');
			$channel = $channelModel->where($where)->find();
			/* $channel = $channelModel->search($where); */
			//dump($channel);exit;
			//$channel=$channelModel->getSumuserChannelList($channel['data']);
			//$channel=$channelModel->getSumChannelList($channel);
			//$channel=$channel[0];
			cookie('pid',$channel['pid']);
			cookie('channelid',$channel['channelid']);
			cookie('adpower',$channel['adpower']);
			//var_dump($channel['adpower']);exit;
			
			cookie('channelname',$channel['channelname']);
			
			$this->assign('ischannelname',$channel['channelname']);
			
			$this->assign('channelid',$channel['channelid']);
			
			$this->assign('ischannel',1);

			$this->assign('channel',$channel);

			$adminInfo['name'] = cookie('uname');

            /*统计*/
            $today=date("Ymd",time());
            //渠道用户数据统计
            $userModel=D('User');
            $daysign=$userModel->getdaySignCount(cookie('channelid'));
            $this->assign('daysign',$daysign);

            $dayUserInfo=$userModel->getDayUserInfo($channel['channelid'],1);   /*今日新增用户*/

            $user_file='./userInfo/statistics_'.$channel['channelid'].'.txt';
            $dataUser=file_get_contents($user_file);
            $dataUserArr=json_decode($dataUser,true);
            if($dataUserArr['today']==$today){
                $userInfo=$dataUserArr;
            }else{
                $userInfo=$userModel->getUserInfo($channel['channelid'],1);
            }

            $this->assign('dayUserInfo',$dayUserInfo);
            $this->assign('userInfo',$userInfo);            
            //渠道用户充值记录
            $payModel=D('pay');
            $dayPayInfo=$payModel->dayPayInfo($channel['channelid'],1);  /*今日充值信息*/
	
            $pay_file='./paylogInfo/statistics_'.$channel['channelid'].'.txt';
            $dataPay=file_get_contents($pay_file);
            $dataPayArr=json_decode($dataPay,true);
            if($dataPayArr['today']==$today){
                $payInfo=$dataPayArr;
            }else{
                $payInfo=$payModel->sumPayInfo($channel['channelid'],1);
            }

            $this->assign('dayPayInfo',$dayPayInfo);
            $this->assign('payInfo',$payInfo);
            //公告信息
            $afficheModel=D('Affiche');
            $affInfo=$afficheModel->order('addtime DESC')->find();
            $this->assign('affInfo',$affInfo);
            $data=$afficheModel->search();
            $this->assign('affList',$data['affList']);
            $this->assign('page',$data['pageShow']);

            $this->assign('admin_info',$adminInfo);
			
			$this->display('channelList');
		}
		else
		{
			$url = U('Admin/Admin/Login');
			
			$this->error('获取权限失败，请重新登录！',$url,3);
		}
	}



	public function channelList()
	{
		if(cookie(uid)<=0){
			$url = U('Admin/Admin/Login');
			
			$this->error('请先登录',$url,3);
			
			exit;
		}
        $this->display();
	}
	public function channelListCombine()
    {
    	cookie('pg','1');
        $channelModel=D('Channel');
		$channelid=I('id');/*通过管理员点击渠道进入*/
        /*自渠道信息*/
        if($channelid){
            $where=array('a.channelid='.$channelid);
        }else{
            $where=array('a.channelid='.cookie('channelid'));
        }        
        /* $where=array('a.channelid='.cookie('channelid')); */
        /* $data=$channelModel->search($where);
        $channelSelf=$channelModel->getChanneInfolList($data['data'],1);

        $channelSumPay=$channelModel->getChannelSumPaylog(cookie('channelid')); *//*自渠道总充值*/

        /* foreach($channelSelf as $key=>$val){
            $channelid=$val['channelid'];
            $daySumPay=$channelModel->getDaySumPayByChannelid($channelid);
            $channelSelf[$key]['daysumpaybyid']=$daySumPay;
        } */
		$data=$channelModel->search($where);
        if(!empty($data)){
        	//var_dump($data);
        	if(count($data['data'])==1){
        		
        		$uname = $this->getUname($data['data'][0]['uid']);
        		$data['data'][0]['uname'] = $uname['uname'];
        	}

        }
        $channelSelf=$channelModel->getChanneInfolListCombine($data['data']);
		
		//dump($channelSelf);

        $this->assign('channelSelf',$channelSelf);
        
		$this->assign('channelid',$channelid);
		
		/* $this->assign('channelSumPay',$channelSumPay); */

	    $this->display();
    }
    public function ajaxChannelListCombine()
    {
        $channelModel=D('Channel');
		/* $where=array('a.pid='.cookie('channelid')); */
		$channelid=I('channelid');/*通过后台管理员查看渠道信息传递渠道Id*/
		//$orderby1 = I('orderby1');
		//$orderby2 = I('orderby2');
        if($channelid){
            $where=array('a.pid='.$channelid);
        }else{
            $where=array('a.pid='.cookie('channelid'));
        }
         //edit by muyi 添加搜素渠道功能可以搜索登录名也可以搜素渠道名
        $keyword=I('keyword');
        if($keyword) {
            //如果有关键词就搜素用户名和渠道名都包含关键字的
            $uids = M('system_users')->field('uid')->where(array('uname' => array('like', '%' . $keyword . '%'),'ischannel'=>1))->select();
           //获取关键字的用户ID
            $uidstr='';
            foreach ($uids as $k=>$v){
                if($k==0){
                    $uidstr=$v['uid'];
                }else{
                    $uidstr.=','.$v['uid'];
                }
            }
           //拼装条件
            if($uidstr!=''){
                $where[]=array("a.uid in (".$uidstr.") OR a.channelname LIKE '%".$keyword."%'");
            }else{
                $where[]=array("a.channelname LIKE '%".$keyword."%'");
            }

        }        
        /* $data=$channelModel->search($where);
		
        $channelList=$channelModel->getChanneInfolList($data['data'],1);	
        foreach($channelList as $key=>$val){
            $channelid=$val['channelid'];
            $daySumPay=$channelModel->getDaySumPayByChannelid($channelid);
            $channelList[$key]['daysumpaybyid']=$daySumPay;

            $channelSumPay=$channelModel->getChannelSumPaylog($channelid);
            $channelList[$key]['channelSumpay']=$channelSumPay;
        } */

        //待结算排序
        /*if(empty($orderby1)){
        	$order='';
        }else{
        	if($orderby1=='posttime'){
        		$order = 'a.'.$orderby1.' '.$orderby2;

	        }else{
	        	$order = 'b.'.$orderby1.' '.$orderby2;
	        }
        }*/
        
        //echo $orderby1;
        //echo $order;
		$data=$channelModel->search($where);
        if(!empty($data)){
        	//var_dump($data);
        	
        	foreach($data['data'] as $k => $v){
        		$uname = $this->getUname($v['uid']);
        		$data['data'][$k]['uname'] = $uname['uname'];
        	}
        	//var_dump($data);
        }
        $channelList=$channelModel->getChanneInfolListCombine($data['data']);

        $this->assign('ischannel',1);
        $this->assign('channelList',$channelList);
        $this->assign('page',$data['page']);
        $this->display();
    }
    /***
    *获取渠道登录名
    **/
    public function getUname($uid){
    	$uname = M('system_users')->field('uname,uid')->where(array('uid'=>$uid))->find();
    	return $uname;
    }
    public function channelList1()
    {
        $this->display();
    }
    public function channelList2()
    {
        $this->display();
    }
	
	/**
	 * 添加新渠道
	 */
	public function addEditChannel1()
	{
		$action    = I('action');
		
		if(cookie('uid') && cookie('permissions') == 1)
		{
			$channelID = trim(I('id'));
			
			$channel   = M('distribution_channels')->where(array('channelid' => $channelID))->find();
			
			$distributionUrl = C('DISTRIBUTION_URL');
			
			$channel['url']  = sprintf($distributionUrl,$channel['secretkey'],urlencode($channel['channelname']),urlencode($channel['channeltype']));
			
			$weiXinDistributionUrl = C('WEIXIN_DISTRIBUTION_URL');
			
			$channel['weixinurl']  = sprintf($weiXinDistributionUrl,$channel['secretkey'],urlencode($channel['channelname']),urlencode($channel['channeltype']));
			
			$this->assign('channel',$channel);
			
			if(($_GET['is_ajax'] == 1) && IS_POST)
			{
				$action = trim(I('action'));
				
				if($action == 'add')
				{
					$channelData['channelname']       = trim(I('post.channel_name'));
					
					$channelData['proportion']        = trim(I('post.channel_proportion'));
					
					$channelData['channeltype']       = trim(I('post.channel_type'));
					
					$channelData['proportion']        = trim(I('post.channel_proportion'));
					
					$channelData['readchaptercount'] = trim(I('post.channel_readchaptercount'));
					
					$channelData['secretkey']   = substr(md5($channelData['channelname'] . time() . $channelData['channeltype']),8,16);
					
					$channelData['posttime']    = time();
 				
					$flag = M('distribution_channels')->add($channelData);
					
					if($flag)
					{
						$payLogData['channelid']   = $flag;
						
						$payLogData['channelname'] = $channelData['channelname'];
						
						$payLogData['paidmoney']   = 0;
						
						$payLogData['remainmoney']  = 0;
						
						M('distribution_pay_log')->add($payLogData);
						
						$return_arr = array
						(
							'status' => '1',
							'msg'    => '添加成功',
							'data'   => array('url' => U('Channel/channelList'))
						);
					}
					else
					{
						$return_arr = array
						(
							'status' => '0',
							'msg'    => '添加失败',
							'data'   => array('url' => U('Channel/channelList'))
						);
					}
				}
				elseif($action == 'edit')
				{
					$channelID = trim(I('post.channel_id'));
					
					$channelData['channelname']      = trim(I('post.channel_name'));
					
					$channelData['channeltype']      = trim(I('post.channel_type'));
					
					$channelData['proportion']       = trim(I('post.channel_proportion'));
					
					$channelData['readchaptercount'] = trim(I('post.channel_readchaptercount'));
					
					$flag = M('distribution_channels')->where(array('channelid' => $channelID))->save($channelData);
					
					if($flag)
					{
						$return_arr = array
						(
							'status' => '1',
							'msg'    => '保存成功',
							'data'   => array('url' => U('Channel/channelList'))
						);
						
						$payLogData['channelname'] = $channelData['channelname'];
						
						M('distribution_pay_log')->where(array('channelid' => $channelID))->save($payLogData);
					}
					else
					{
						$tmpChannelInfo = M('distribution_channels')->where(array('channelid' => $channelID))->find();
						
						if($tmpChannelInfo['channelname'] == $channelData['channelname'] && $tmpChannelInfo['proportion'] == $channelData['proportion'] && $tmpChannelInfo['channeltype'] == $channelData['channeltype'])
						{
							$return_arr = array
							(
								'status' => '1',
								'msg'    => '保存成功',
								'data'   => array('url' => U('Channel/channelList'))
							);
						}
						else
						{
							$return_arr = array
							(
								'status' => '0',
								'msg'    => '保存失败',
								'data'   => array('url' => U('Channel/channelList'))
							);
						}
					}
				}
				
				$this->ajaxReturn(json_encode($return_arr));
			}
			
			$this->assign('action' , $action);
			
			$this->display();
		}
		else
		{
			$this->display('Admin/Login');
		}
	}
	
	
	
	/**
	 * 添加编辑主新渠道
	 */
	public function addEditChannel()
	{
		$action    = I('action');
		if(cookie('uid')==1 && cookie('permissions') == 1)
		{
            $channelModel=D('Channel');
            $channelUserModel=M('system_users');
            $channelid=I('id');
            $channel=$channelModel->find($channelid);
            if (!empty($channel['uid'])) {
                $user = $channelUserModel->find($channel['uid']);
            }
            $channel['uname']=$user['uname'];
			if(IS_POST)
			{

			    $action = trim(I('action'));
				if($action == 'add')
				{
				    $res=$channelModel->addSchannle();
				    if($res){
                        $this->success('添加渠道成功',U('channelList'));exit;
                    }else{
				        $this->error('添加渠道失败!'.$channelModel->getError());exit;
                    }

				}
				elseif($action == 'edit')
				{
                    if (!empty($_POST['pass']) && !empty($_POST['uid'])) {
                        $_POST['pass'] = encrypt($_POST['pass']);
                         $channelUserModel->save($_POST);
                    } else {
                        //如果用户名不为空添加用户名
                        if (!empty($_POST['uname'])) {
                            $usercount = $channelUserModel->where(array('uname' => I('uname')))->count();

                            if ($usercount > 0) {
                                $this->error('用户名已存在');
                                exit;
                            } else {
                                //如果密码为空自动用6个1
                                if (empty($_POST['pass'])) {
                                    $_POST['pass'] = '111111';
                                }
                                $_POST['pass'] = encrypt($_POST['pass']);
                                $_POST['faceImg'] = 'http://img.mianfeidushu.com/facePic/01.png';
                                $_POST['ischannel'] = '1';
                                $_POST['ischanneladmin'] = '0';
                                $_POST['ischannelbind'] = '1';
                                $uid = $channelUserModel->add($_POST);
                                //添加用户成功后返回uid作为新增渠道用户登录使用
                                if ($uid > 0) {
                                    $_POST['uid'] = $uid;
                                } else {
                                    $this->error($channelUserModel->getError());

                                }
                            }
                        }

                    }

                    $res = $channelModel->save($_POST);
                    if ($res !== false) {
                        $this->success('修改渠道成功', U('channelList'));
                        exit;
                    } else {
                        $this->error($channelModel->getError());
                        exit;
                    }

				}
			}
			
			$this->assign('action' , $action);
			$this->assign('channel' , $channel);

			$this->display();
		}
		else
		{
			$this->display('Admin/Login');
		}
	}
	
	
	
	
	/**
	 * 加载渠道列表
	 */
	public function ajaxChannelList2()
	{
		if(cookie('permissions') == 0)
		{
			if(cookie('channelname'))
			{
				$keyWord   = cookie('channelname');
				
				$isChannel = 1;
				
				$this->assign('ischannel',$isChannel);
				
				$channelInfo = M('distribution_channels')->where(array('uid' => cookie('uid')))->find();
				
				$condition['channelid'] = $channelInfo['channelid'];
			}
			else
			{
				$channelList = array();
				
				$Page        = new AjaxPage(0,10);
				
				$show        = $Page->show();
				
				$this->assign('channelList',$channelList);
				
				$this->assign('page',$show);// 赋值分页输出
				
				$this->display();
				
				exit();
			}
		}
		else
		{
			$keyWord = I('key_word');
		}
		
		if(cookie('uid'))
		{
			$condition['channelname'] = array('like','%' . $keyWord . '%');
			
			$count       = M('distribution_channels')->where($condition)->count();
			
			$Page        = new AjaxPage($count,10);
			
			$show        = $Page->show();
			
			$channelList = M('distribution_channels')->where($condition)->limit($Page->firstRow . ',' . $Page->listRows)->select();
			
			$channelList = convert_arr_key($channelList,'channelid');

			
			foreach($channelList as $key => $value)
			{
				$channelList[$key] = $this->getChannelPayLog($value['channelid']);
			}
			$this->assign('channelList',$channelList);
			
			$this->assign('page',$show);// 赋值分页输出
			
			$this->display();
		}
	}


    /**
     * edit by muyi 2017.05.03
     * ajax获取渠道列表信息
     */
    public function ajaxChannelList()
    {
        //后台管理员和渠道用户分开判断
        $channelModel=D('Channel');
        if(cookie('permissions')==1&&cookie('uid')==1){
            $where=array('a.pid'=>0);
            $data=$channelModel->search($where,15);
            foreach($data['data'] as $k=>$v){
                $channelid=$v['channelid'];
                $daySumpay=$channelModel->getDaySumPay($channelid);
                $data['data'][$k]['daysumpay']=$daySumpay;

                $channelids=M('distribution_channels')->field('channelid')
                ->where(array('pid'=>$v['channelid']))
                ->select();
                //var_dump($channelids);exit;
	            foreach($channelids as $val){
	                $channelidArr[]=$val['channelid'];
	            }
	            $channelidArr[] = $v['channelid'];
	            $where1['channelid'] = array('IN',$channelidArr);
	            $where1['payflag'] = 1;
	            
	            $sumpays = M('distribution_pay_paylog')->field("sum(money) as summoneys")->where($where1)->select();
	            unset($channelidArr);
	            //echo M()->getLastSql();exit;
	            //var_dump($sumpays);exit;
	            $sumpays=$sumpays[0]['summoneys'];
	            if(!$sumpays){
	            	$sumpays =0;
	            }
	            $data['data'][$k]['sumpays']=$sumpays;
            }

            /* $data['data']=$channelModel->getSumChannelList($data['data']); */
        }else{
            $where=array('a.channelid='.cookie('channelid').' or a.pid='.cookie('channelid'));
            $data=$channelModel->search($where);
            $this->assign('ischannel',1);
        }
        $channelLists=$data['data'];
        $channelList = array();
        foreach($channelLists as $val){
        	$uname = $this->getUname($val['uid']);
        	$val['uname'] = $uname['uname'];
        	//var_dump($val);exit;
        	$channelList[] = $val;
        }
        //var_dump($channelList);
        $this->assign('channelList',$channelList);
        $this->assign('page',$data['page']);
        $this->display();
    }



	
	/**
	 * 结算接口
	 */
    public function settlement()
    {
    	if(cookie('uid') && cookie('permissions') == 1)
	    {
		    $id = I('id');
		
		    $settlement = $this->getChannelPayLog($id);
		    
		    if(($_GET['is_ajax'] == 1) && IS_POST)
		    {
			    $action = trim(I('action'));
			
			    if($action == 'settlement')
			    {
				    $channelID   = I('channelid');
				
				    $channelName = I('channelname');
				
				    $payInfo = M('distribution_pay_log')->where(array('channelid' => $channelID,'channelname' => $channelName))->find();
				
				    $convertProportion = C('CONVERTIBLE_PROPORTION');//兑换比例
				    
				    $money = I('money') / $convertProportion;
				
				    if(!$money)
				    {
					    $return_arr = array
					    (
						    'status' => '1',
						    'msg'    => '结算成功',
						    'data'   => array('url' => U('Channel/channelList'))
					    );
				    }
				    else if($payInfo['remainmoney'] >= $money)
				    {
					    $data['lastpaytime'] = time();
					
					    $data['paidmoney'] = $payInfo['paidmoney'] + $money;
					
					    $data['remainmoney'] = $payInfo['remainmoney'] - $money;
					
					    $flag = M('distribution_pay_log')->where(array('channelid' => $channelID))->save($data);
					
					    if($flag)
					    {
						    $return_arr = array('status' => '1', 'msg' => '结算成功', 'data' => array('url' => U('Channel/channelList')));
					    }
					    else
					    {
						    $return_arr = array('status' => '0', 'msg' => '结算失败', 'data' => array('url' => U('Channel/channelList')));
					    }
				    }
				    else
				    {
					    $return_arr = array
					    (
						    'status' => '0',
						    'msg'    => '结算失败',
						    'data'   => array('url' => U('Channel/channelList'))
					    );
				    }
				
				    $this->ajaxReturn(json_encode($return_arr));
			    }
		    }
		
		    $this->assign('settlement',$settlement);
		
		    $this->display();
	    }
	    else
	    {
		    $this->display('Admin/Login');
	    }
    }


    /**
     * edit by muyi 2017.05.05
     * 渠道结算
     */

    public function channelSettlement()
    {
        if(cookie('permissions')==1&&cookie('uid')==1){
            $channelid=I('id');
            $channelModel=D('Channel');
            $res=$channelModel->settlement($channelid);
            if($res!==false){
                $this->success('结算成功',U('channelList'));
            }else{
                $this->error('结算失败'.$channelModel->getError(),U('channelList'));
            }
        }else{
            $this->error('没有该权限!');
        }
        
    }
/**
*删除推广文案连接
**/
	public function delPt(){
		$ptid = I('post.ptid');
		$data = array();
		if(!is_numeric($ptid)){
			$data['status'] = 0;
			$data['msg'] = "参数不合法";
			
		}

		$delstatus = M('distribution_channel_pt')->where(array('ptid'=>$ptid))->delete();
		if($delstatus){
			$data['status'] = 1;
			$data['msg'] = "success";
			
		}else{
			$data['status'] = 0;
			$data['msg'] = "error 删除失败";
			
		}
		$this->ajaxReturn($data);
	}
	/**
	 * 查看渠道的书籍销售情况
	 */
	public function delChannel()
	{
		if(cookie('uid') && cookie('permissions') == 1)
		{
			$id      = I('id');
			
			$oldData = M('distribution_channels')->where(array('channelid' => $id))->select();
			$cuid = $oldData[0]['uid'];
			
			$flag    = M('distribution_channels')->where(array('channelid' => $id))->delete();
			
			if($flag)
			{
				$flag2    = M('system_users')->where(array('uid' => $cuid))->delete();
				$flag = M('distribution_pay_log')->where(array('channelid' => $id))->delete();

				if($flag)
				{
					
					$return_arr = array
					(
						'status' => '1',
						'msg'    => '删除成功',
						'data'   => array('url' => U('Channel/channelList'))
					);
					
					
				}
				else
				{
					$data = M('distribution_pay_log')->where(array('channelid' => $id))->select();
					
					if(!$data)
					{
						$return_arr = array
						(
							'status' => '1',
							'msg'    => '删除成功',
							'data'   => array('url' => U('Channel/channelList'))
						);
					}
					else
					{
						M('distribution_channels')->add($oldData);
						
						$return_arr = array
						(
							'status' => '0',
							'msg'    => '删除失败',
							'data'   => array('url' => U('Channel/channelList'))
						);
					}
				}
			}
			else
			{
				$return_arr = array
				(
					'status' => '0',
					'msg'    => '删除失败',
					'data'   => array('url' => U('Channel/channelList'))
				);
			}
		}
		else
		{
			$this->display('Admin/Login');
		}
		
		$this->ajaxReturn(json_encode($return_arr));
	}
	
	/**
	 * 绑定渠道用户id
	 */
	public function bindUserChannel()
	{
		if(cookie('uid') && cookie('permissions') == 1)
		{
			$channelInfo = I();
			
			$channelInfo = M('distribution_channels')->where(array('channelid' => $channelInfo['id']))->find();
			
			$this->assign('channelinfo',$channelInfo);
			
			$tmpUserList = M('system_users')->where(array('ischannel' => 1))->select();
			
			foreach($tmpUserList as $key => $value)
			{
				$userInfo['uid']  = $value['uid'];
				
				$userInfo['name'] = $value['uname'];
				
				$userList[]       = $userInfo;
			}
			
			if(($_GET['is_ajax'] == 1) && IS_POST)
			{
				$data['uid'] = trim(I('uid'));
				
				if($data['uid'])
				{
					$channelID   = trim(I('channel_id'));
					
					$flag        = M('distribution_channels')->where(array('channelid' => $channelID))->save($data);
					
					if($flag)
					{
						$userData['ischannelbind'] = 1;
						
						$flag = M('system_users')->where(array('uid' => $data['uid']))->save($userData);
						
						if($flag)
						{
							$return_arr = array
							(
								'status' => '1',
								'msg'    => '绑定成功',
								'data'   => array('url' => U('Channel/channelList'))
							);
						}
						else
						{
							$channel = M('distribution_channels')->where(array('channelid' => $channelID))->find();
							
							if($channel['uid'] == $data['uid'])
							{
								$return_arr = array
								(
									'status' => '1',
									'msg'    => '绑定成功',
									'data'   => array('url' => U('Channel/channelList'))
								);
							}
							else
							{
								$data['uid'] = 0;
								
								M('distribution_channels')->where(array('channelid' => $channelID))->save($data);
								
								$return_arr = array
								(
									'status' => '0',
									'msg'    => '绑定失败',
									'data'   => array('url' => U('Channel/channelList'))
								);
							}
						}
					}
					else
					{
						$channel = M('distribution_channels')->where(array('channelid' => $channelID))->find();
						
						if($channel['uid'] == $data['uid'])
						{
							$return_arr = array
							(
								'status' => '1',
								'msg'    => '绑定成功',
								'data'   => array('url' => U('Channel/channelList'))
							);
						}
						else
						{
							$return_arr = array
							(
								'status' => '0',
								'msg'    => '绑定失败',
								'data'   => array('url' => U('Channel/channelList'))
							);
						}
					}
				}
				else
				{
					$return_arr = array
					(
						'status' => '0',
						'msg'    => '请选择用户',
						'data'   => array('url' => U('Channel/bindUserChannel',array('id' => $channelInfo['id'],'channelname' => $channelInfo['channelname'])))
					);
				}
				
				$this->ajaxReturn(json_encode($return_arr));
			}
			
			$this->assign('userlist',$userList);
			
			$this->display();
		}
		else
		{
			$this->display('Admin/Login');
		}
	}

	/**
	 * 根据$channelID获取渠道的结算信息
	 *
	 * @param $channelID
	 * @return mixed
	 */
	private function getChannelPayLog($channelID)
	{
		$channelPayLog = M('distribution_pay_log')->where(array('channelid' => $channelID))->find();
		
		$channelInfo   = M('distribution_channels')->where(array('channelid' => $channelID))->find();

		$channelPayInfo['channelid']   = $channelInfo['channelid'];
		
		$channelPayInfo['channelname'] = $channelInfo['channelname'];
		
		$channelPayInfo['summoney']    = ($channelPayLog['paidmoney'] + $channelPayLog['remainmoney']);
		
		$channelPayInfo['remainmoney'] = $channelPayLog['remainmoney'] * $channelInfo['proportion'];
		
		$channelPayInfo['proportion']  = $channelInfo['proportion'];
		
		$channelPayInfo['paidmoney']   = $channelPayLog['paidmoney'] ? $channelPayLog['paidmoney']  : 0;
		
		return $channelPayInfo;
	}

	public function showChannelInfo()
	{
		$channelID = I('id');
		
		$channel   = M('distribution_channels')->where(array('channelid' => $channelID))->find();
		
		$distributionUrl = C('DISTRIBUTION_URL');
		
		$channel['url']  = sprintf($distributionUrl,$channel['secretkey'],urlencode($channel['channelname']),urlencode($channel['channeltype']));
		
		$weiXinDistributionUrl = C('WEIXIN_DISTRIBUTION_URL');
		
		$channel['weixinurl']  = sprintf($weiXinDistributionUrl,$channel['secretkey'],urlencode($channel['channelname']),urlencode($channel['channeltype']));
		
		$this->assign('channel',$channel);
		
		$this->display();
	}


    /**
     * 获取渠道信息
     */

	public function getChannelInfo()
	{
		$channelID = I('id');
	
		if(cookie('permissions') == 0)
		{
			$this->assign('ischannel',1);
			
			$channelInfo = M('distribution_channels')->where(array('channelid' => $channelID))->find();
			
			$this->assign('channel',$channelInfo);
			
			$this->display();
		}
		else
		{
			$channelInfo = M('distribution_channels')->where(array('channelid' => $channelID))->find();
			
			$this->assign('channel',$channelInfo);
			
			$this->display();
		}
	}



       /**
     * edit by muyi
     * 日期 2017/05/12
     * 增加子渠道
     */
    public function addSchannel()
    {
        //增加子渠道
        $channel=D('Channel');
        if(IS_POST){
            $res=$channel->addSchannle();
            if($res){
                $this->success('添加成功',U('index'));
                exit();
            }else{
                $this->error($channel->getError(),U('addSchannel'));
            }
        }
        if(cookie('permissions') == 0){
            $this->assign('ischannel',1);
        }
        $this->display();
    }
    /**
     * edit by muyi 2017.05.05
     * 修改子渠道基本信息
     */
    public function editSChannel()
    {
        $id = I('id');
        $channelModel = D('channel');
        $channelUserModel = D('system_users');
        if (IS_POST) {
            if (!empty($_POST['pass']) && !empty($_POST['uid'])) {
                $_POST['pass'] = encrypt($_POST['pass']);
                $channelUserModel->save($_POST);
            } else {
                //如果用户名不为空添加用户名
                if (!empty($_POST['uname'])) {
                    $usercount = $channelUserModel->where(array('uname' => I('uname')))->count();

                    if ($usercount > 0) {
                        $this->error('用户名已存在');
                        exit;
                    } else {
                        //如果密码为空自动用6个1
                        if (empty($_POST['pass'])) {
                            $_POST['pass'] = '111111';
                        }
                        $_POST['pass'] = encrypt($_POST['pass']);
                        $_POST['faceImg'] = 'http://img.mianfeidushu.com/facePic/01.png';
                        $_POST['ischannel'] = '1';
                        $_POST['ischanneladmin'] = '0';
                        $_POST['ischannelbind'] = '1';
                        $uid = $channelUserModel->add($_POST);
                        //添加用户成功后返回uid作为新增渠道用户登录使用
                        if ($uid > 0) {
                            $_POST['uid'] = $uid;
                        } else {
                            $this->error($channelUserModel->getError());exit;                      
                        }
                    }
                } 
			}	

                $res = $channelModel->save($_POST);
                if ($res !== false) {
                    $this->success('修改子渠道成功', U('channelListCombine'));
                    exit;
                } else {
                    $this->error($channelModel->getError());
                    exit;
                }
            
        }
            $data = $channelModel->find($id);
            if (!empty($data['uid'])) {
                $user = $channelUserModel->find($data['uid']);
            }
            $this->assign('data', $data);
            $this->assign('user', $user);
            $this->display();


    }
    
    
    
    /**
     * edit by muyi 2017.05.05
     * 导出渠道结算信息
     */

    public function outSettlement()
    {
        //取出数据
        $channelModel=D('Channel');
        if(cookie('permissions')==1&&cookie('uid')==1){
            $where=array('a.pid'=>0);
            $data=$channelModel->search($where, PHP_INT_MAX);//全部取出
			$channelList=$data['data'];
			foreach($channelList as $k=>$v){
				 $daySumpay=$channelModel->getDaySumPay($v['channelid']);
				 $channelList[$k]['remainmoney']=$v['remainmoney']-$daySumpay;				
			}
			
        //引入Excel类库
            //引入phpExcel类库
            vendor('Excel.PHPExcel','','.php');
            $objPHPExcel = new \PHPExcel();
            // 设置文档属性
            $objPHPExcel->getProperties()->setCreator("Maarten Balliauw")
                ->setLastModifiedBy("Maarten Balliauw")
                ->setTitle("Office 2007 XLSX Test Document")
                ->setSubject("Office 2007 XLSX Test Document")
                ->setDescription("Test document for Office 2007 XLSX, generated using PHP classes.")
                ->setKeywords("office 2007 openxml php")
                ->setCategory("Test result file");
            // 设置表头
            $objPHPExcel->setActiveSheetIndex(0)
                ->setCellValue('A1', '渠道ID')
                ->setCellValue('B1', '渠道名称')
                ->setCellValue('C1', '渠道分成比例')
                ->setCellValue('D1', '总收益（元）')
                ->setCellValue('E1', '已结算（元）')
                ->setCellValue('F1', '待结算（元）');
            //设置表格宽度
            $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(25);
            $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(15);
            $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(15);
            $objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(15);
            $objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(15);
            $count=count($channelList);
//            echo '<pre>';
//            var_dump($channelList);die;
            //设置表格内容
            for($i=2;$i<=$count+1;$i++){
                $sumMoney=round($channelList[$i-2]['paidmoney']/$channelList[$i-2]['proportion']+$channelList[$i-2]['remainmoney'],2);
                $objPHPExcel->setActiveSheetIndex(0)
                    ->setCellValue('A'. $i,$channelList[$i-2]['channelid'])
                    ->setCellValue('B'. $i,$channelList[$i-2]['channelname'])
                    ->setCellValue('C'. $i,$channelList[$i-2]['proportion'] )
                    ->setCellValue('D'. $i,$sumMoney)
                    ->setCellValue('E'. $i, round($channelList[$i-2]['paidmoney'],2))
                    ->setCellValue('F'. $i,round($channelList[$i-2]['remainmoney']*$channelList[$i-2]['proportion'],2));
            }

            //设置表格名称
            $objPHPExcel->getActiveSheet()->setTitle('渠道收益结算'.date("Y年m月d日",time()));
            // Redirect output to a client’s web browser (Excel2007)
            header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Content-Disposition: attachment;filename="渠道收益结算表-'.date("YmdHis",time()).'.xlsx"');
            header('Cache-Control: max-age=0');
            // If you're serving to IE 9, then the following may be needed
            header('Cache-Control: max-age=1');

            // If you're serving to IE over SSL, then the following may be needed
            header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
            header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
            header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
            header ('Pragma: public'); // HTTP/1.0

            $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
            $objWriter->save('php://output');
            exit;


        }else{
            $this->error('没有权限');
        }
    }


    /**
     * edit by muyi 2017.05.05
     * 一键结算
     */

    public function batSettlement()
    {
        if(cookie('permissions')==1&&cookie('uid')==1){
            $channelModel=D('Channel');
            $res=$channelModel->batSettlement($channelid);
            if($res!=false){
                $this->success('结算成功',U('channelList'));
            }else{
                $this->error('结算失败'.$channelModel->getError(),U('channelList'));
            }
        }else{
            $this->error('没有该权限!');
        }
    }
	
	
	
    /**
     * edit by muyi  2017/05/
     * 渠道财务信息添加和修改
     */
    public function channelBankinfo()
    {
        $action=I('action');
        $cid = I('id');
        $channelModel=D('Channel');
        $infoModel=M('distribution_channel_info');
        if(IS_POST){

            //如果是编辑财务信息更新
            if($action=='edit'||$_POST['infoid']!==''){
                if(cookie('permissions')==1&&cookie('uid')==1){
                    $res=$infoModel->where(array('infoid'=>I('infoid')))->save($_POST);
                }elseif(cookie('permissions')==0&&cookie('uid')>0&&cookie('cpid')==0&&$_POST['cid']){
                	
                	$res=$infoModel->where(array('infoid'=>I('infoid')))->save($_POST);
                }else{
                    //如果是用户防止修改银行财务信息
                    if($action!='add'){
                        unset($_POST['bank']);
                        unset($_POST['bankname']);
                        unset($_POST['banknum']);
                    }
                    $res=$infoModel->where(array('infoid'=>I('infoid')))->save($_POST);
                }

            }
            if($action=='add'&&$_POST['infoid']==''){
                $res=$infoModel->add($_POST);
                }

                if($res!==false){
                    $this->success('财务信息保存成功!');
                    exit;
                }else{
                    $this->error('财务信息保存失败'.$infoModel->getError());
                    exit;
                }
        }else{
            //如果是管理员直接编辑信息
            if(cookie('permissions')==1&&cookie('uid')==1){
                $channel=$channelModel->getChannelBankinfo(I('id'));
                //判断当前渠道有没有绑定个用户没绑定过用户的不是主渠道
                if(empty($channel['userid'])){
                    $this->error('该渠道还没有绑定用户');
                    exit;
                }
            }else {
                //如果当前渠道没有绑定渠道先不添加财务信息
                if(cookie('uid')>0 && cookie('channelid')>0){
                	if(cookie('cpid')>0){
	                	$uname = $this->getUname(cookie('uid'));
	                    $channel=$channelModel->getChannelBankinfo(cookie('channelid'));
	                    $channel['uname'] = $uname['uname'];
	                }else{
	                	if($cid){
	                		$cuid = M('distribution_channels')->where(array('channelid'=>$cid))->find();
	                		$uname = $this->getUname($cuid['uid']);
	                		$channel=$channelModel->getChannelBankinfo($cid);
	                    	$channel['uname'] = $uname['uname'];
	                	}else{
	                		$uname = $this->getUname(cookie('uid'));
	                		$channel=$channelModel->getChannelBankinfo(cookie('channelid'));
	                    	$channel['uname'] = $uname['uname'];
	                	}
	                }
                }else{

                    $this->error('您还没有绑定渠道请联系渠道管理员!',U('index'));
                    exit;
                }
           } 
            //如果银行帐号不存在证明就认为没有添加过
            if(empty($channel['banknum'])){
                $action='add';
            }else{
                $action='edit';
            }

        }
        if(!empty($cid)){
        	$this->assign('cid',$cid);
        }
        $this->assign('channel',$channel);
        $this->assign('userinfo',$uname);
        $this->assign('action',$action);
        $this->display();
    }

    /**
     * 渠道推广信息列表
     */
    public function channelInfoList()
    {
        $this->display();
    }

    /**
     * ajax获取渠道推广信息列表
     */
    public function ajaxChannelInfoList()
    {
        //后台管理员和渠道用户分开判断
        $channelModel=D('Channel');
        if(cookie('permissions')==1&&cookie('uid')==1){
            $where=array('a.pid'=>0);
            $data=$channelModel->search($where,15);
            $data['data']=$channelModel->getChanneInfolList($data['data']);
            foreach($data['data'] as $key=>$val){
                $channelid=$val['channelid'];
                $daySumPay=$channelModel->getDaySumPay($channelid);
                $data['data'][$key]['daysumpay']=$daySumPay;
            } 
        }else{
            $where=array('a.channelid='.cookie('channelid').' or a.pid='.cookie('channelid'));
            $data=$channelModel->search($where);
            $data['data']=$channelModel->getChanneInfolList($data['data'],1);
            $this->assign('ischannel',1);
        }
        $channelList=$data['data'];
        //dump($channelList);exit();
        $this->assign('channelList',$channelList);
        $this->assign('page',$data['page']);
        $this->display();

    }
    /**
     * 渠道公告信息
     */
    public function channelAffiche(){
        $affiche=D('Affiche');
        //搜索关键字
        $keyword=I('keyword');
        if($keyword){
            $condition['content']=array('LIKE','%'.$keyword.'%');
        }
        $parameter=array('keyword'=>$keyword);
        /* 分页 */
        $totalRow = $affiche->count();
        $pageSize=12;
        $page = new Page($totalRow,$pageSize,$parameter);
        $page->setConfig('prev', '上一页');
        $page->setConfig('next', '下一页');
        $page->setConfig('first', '首页');
        $page->setConfig('last', '尾页');
        $pageShow= $page->show();

        $affList=$affiche->order('addtime DESC')
            ->where($condition)
            ->limit($page->firstRow.','.$page->listRows)
            ->select();
        $this->assign('page',$pageShow);
        $this->assign('keyword',$keyword);
        $this->assign('affList',$affList);
        $this->display();
    }
	/**
     * 渠道微信服务号的设置
     */
    public function wxSet()
    {
        //如果有POST数据就添加或者更新数据
        if(IS_POST){
            $channelWxModel=M('distribution_channel_wx');
            if($_POST['action']=='add'){
                $res=$channelWxModel->add(I('post.'));
                if($res){
                    $this->success('公众号信息添加成功!');
                    exit;
                }else{
                    $this->error('公众号信息添加失败'.$channelWxModel->getError());
                    exit;
                }
            }else{
                $res=$channelWxModel->where(array('channelid'=>I('post.channelid')))->save(I('post.'));
                if($res!==false){
                    $this->success('公众号信息修改成功!');
                    exit;
                }else{
                    $this->error('公众号信息修改失败:'.$channelWxModel->getError());
                    exit;
                }

            }


        }else{//没有就显示数据
            $channelModel=D('Channel');
            $wxinfo=$channelModel->getWxInfo();
           if($wxinfo){//获取到渠道微信公众号信息就编辑
               $action='edit';
               $this->assign('wxinfo',$wxinfo);
           }else{//没有获取到就添加
               $action='add';
           }

           $this->assign('action',$action);
           $this->assign('channelid',cookie('channelid'));
        }

        $this->display();
    }
	
	
	 /**
     * 微信公众号自定义菜单生成
     */

    public function wxMenu()
    {
        //获取当前渠道id
        $channelid=cookie('channelid');
        $channelWxModel=M('distribution_channel_wx');
        //请求url地址
        $menuUrl="http://wap.kyread.com/wx/createMenu/id/$channelid.html";
        $count=$channelWxModel->where(array('channelid'=>$channelid))->count();
        if($count>0){
            $str=request($menuUrl,0);
            $pos=strpos($str,'ok');
            if($pos){
                $this->success('公众号自定义菜单设置成功!',U('index'),5);
            }else{
                $this->error('公众号自定义菜单设置失败!',U('index'),5);
            }
        }else{
            $this->error('还未设置公众号信息,请先设置公众号信息!',U('index'),5);
        }
    }
	
	
	
    /**
     * 获取模版消息
     */

    public function tplList()
    {
        $tplModel=M('distribution_channel_tplinfo');
        $channelid=cookie('channelid');
        $tpllist=$tplModel->where('channelid = '.$channelid)->order(' id desc')->select();

        $this->assign('tpllist',$tpllist);
        $this->display();



    }


    /**
     * 添加模版
     */

    public function tplAdd()
    {
        $tplModel=M('distribution_channel_tplinfo');
        if(IS_POST){
            $channelid=I('post.channelid');
            $tpl=$this->savetpl();
            if ($tpl){

                if(I('post.action')=='add'){
                    $this->success('模版消息保存成功!',U('Channel/tplList'));
                    exit;
                }
		 if(I('post.action')=='send'){
                   $count = $this->sendAll($channelid,$tpl);
                   $data['id']=$tpl['id'];
                   $data['sendtime']=time();
                   $data['sendcount']=$count['sendcount'];
                   $data['okcount']=$count['okcount'];
                   $data['issend']=1;
                   $tplModel->save($data);
                   $this->success('模版消息已发送!,发送人数:'.$data['sendcount'],U('Channel/tplList'));
                   exit;
                }

            }else{
                $this->error('模版消息保存失败!');
                exit;
            }
        }

        $this->display();

    }

    /**
     * 给自己测试发送
     */
    public function testSend()
    {
	$action='test';
        $tpl=$this->savetpl($action);
        if($tpl){
            $uid=I('post.uid');
            //获取测试用户的openid
            $userModel=D('User');
            $user=$userModel->getUnameById($uid);
			$openid=$user['uname'];
            $name=$user['name'];
            //获取token
            $channelid=I('post.channelid');
            $token=$this->getToken($channelid);
            //发送
            $res=$this->sendtpl($openid,$name,$tpl,$token);
            if($res){
                echo '发送成功!如果未接收到请修改参数!';
            }else{
                echo '发送失败!';
            }
        }

    }

    /**
     * 保存过的未发送的模版消息点击发送
     */
    public function sendInfo1()
    {
        $infoid=I('get.id');
        $tplModel=M('distribution_channel_tplinfo');
        $tpl=$tplModel->find($infoid);
        $count=$this->sendAll($tpl['channelid'],$tpl);
        $data['id']=$tpl['id'];
        $data['sendtime']=time();
        $data['sendcount']=$count['sendcount'];
        $data['okcount']=$count['okcount'];
        $data['issend']=1;
        $tplModel->save($data);
        $this->success('模版消息已发送!,发送人数:'.$data['sendcount'],U('Channel/tplList'));

    }
	
	
	/**
     * 保存过的未发送的模版消息按时发送
     */
    public function sendInfo()
    {
		
        $curtime=time()+60;
        $tplModel=M('distribution_channel_tplinfo');
        $tpl=$tplModel->where('sendtime < '.$curtime.' AND issend = 0')
            ->order('id ASC')
            ->limit(1)
            ->select();
			 $tpl=$tpl[0];			
		if($tpl['id']>0){
            //改变当前状态发送中
            $tpl['issend']=-1;
            $tplModel->save($tpl);
            //写入日志开始时间
            $str=$tpl['id'].' 号模版开始发送------'.date('Y-m-d H:i:s',time());
            file_put_contents('./sendlog.txt',$str.PHP_EOL,FILE_APPEND);

            $count=$this->sendAll($tpl['channelid'],$tpl);
            $data['id']=$tpl['id'];
            $data['sendtime']=time();
            $data['sendcount']=$count['sendcount'];
            $data['okcount']=$count['okcount'];
            $data['issend']=1;
            $tplModel->save($data);
            ////写入日志完成时间
            $str=$data['id'].' 号模版已发送完毕,发送人数 '.$data['sendcount'].',成功:'. $data['okcount'].'-----'.date('Y-m-d H:i:s',time());
            file_put_contents('./sendlog.txt',$str.PHP_EOL,FILE_APPEND);
        }

    }


    /**
     * 发送给当前渠道的所有用户!关注公众号的用户
     */

    public function sendAll($channelid,$tpl)
    {
        //获取渠道用户uname
        $userModel=D('User');
        $userlist=$userModel->getUserUnameListByfromid($channelid);
        $count['sendcount']=0;
        $count['okcount']=0;
        //发送模版消息
        foreach ($userlist as $k =>$v){
            $count['sendcount']++;
            $token=$this->getToken($channelid);
           // echo $token,'<br/>'; 
		   //echo$v['uname'],'<br>';
            $res=$this->sendtpl($v['uname'],$v['name'],$tpl,$token);
            if($res){
                $count['okcount']++;
            }
        }

        return $count;
    }

    /**
     * 保存模版
     */
    public function savetpl()
    {
        $tplModel=M('distribution_channel_tplinfo');
        $tpldata=array();
        $tplpost=(I('post.'));
        foreach ($tplpost as $k=>$v){
            if (is_array($v)){
                $tpldata[$v[0]]['value']=$v[1];
                $tpldata[$v[0]]['color']=$v[2];
            }
        }
       $tpldata=json_encode($tpldata);
        $tpl['channelid']=$tplpost['channelid'];
        $tpl['template_id']=$tplpost['template_id'];
        $tpl['url']=$tplpost['url'];
        $tpl['title']=$tplpost['title'];
        $tpl['tpltitle']=$tplpost['tpltitle'];
        $tpl['sendtime']= strtotime($tplpost['sendtime']);
        $tpl['data']=$tpldata;
        $tpl['addtime']=time();

        //如果是测试的话不保存
        if($tplpost['action']=='test'){
            return $tpl;
        }else{
            $res=$tplModel->add($tpl);
            if($res){
                $tpl['id']=$res;
                return $tpl;//如果添加成功,返回模版信息
            }else{
                return false;
            }
        }

    }

    /**
     * 发送模版消息
     */

    public function sendtpl($openid,$name='',$tpl ,$token)
    {
        $sendtpl['touser']=$openid;
        $sendtpl['template_id']=$tpl['template_id'];
        $sendtpl['url']=$tpl['url'];
		
		if($name==''){
			$name='小主 ';
		}
		$tpl['data']=str_replace('{wxname}',$name,$tpl['data']);
		//var_dump($tpl['data']);exit;
        $sendtpl['data']=json_decode($tpl['data'],true);
        $sendData=json_encode($sendtpl);
        $url='https://api.weixin.qq.com/cgi-bin/message/template/send?access_token='.$token;
        $res=request($url, true, "post", $sendData);
        $res=json_decode($res,true);

        if($res['errmsg']=='ok'){
            return true;
        }else{
            return false;
        }

    }

    /**
     * 从微信服务器获取该公众号的模版列表
     */
    public function getTplList()
    {
        //获取token
        $channelid=I('get.id');
        $token=$this->getToken($channelid);
        //获取模版消息
        $tplurl="https://api.weixin.qq.com/cgi-bin/template/get_all_private_template?access_token=".$token;

        $tpl=request($tplurl,1);
        $tpl=json_decode($tpl,0);
        $tpl=$tpl->template_list;
        $tpl=json_encode($tpl);
        echo $tpl;

    }

    /**
     * 获取token
     */

    public function getTokenByUrl($channelid)
    {
        if(empty($channelid)){
            $channelid=cookie('channelid');
        }
        $tokenUrl="http://wap.kyread.com/wx/getToken/id/$channelid.html";
        $token=request($tokenUrl,0);
        return $token;

    }
	
	/**
	*获取token从数据库获取
	**/
	
	public function getToken($channelid){
		$channelWxModel = M('distribution_channel_wx');
        $wxinfo = $channelWxModel->where(array('channelid' =>$channelid))->find();
		 if ($wxinfo) {
                if ((!empty($wxinfo['atoken']) && !empty($wxinfo['tokentime']) && (time() - $wxinfo['tokentime'] > 600))||empty($wxinfo['atoken'])) {
                    $content = request("https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=".$wxinfo['appid']."&secret=".$wxinfo['appsecret']); //获取access token的json对象
                    file_put_contents($file, $content); //保存json对象到指定文件
                    $content = json_decode($content);//进行json解码
                    $wxtoken['atoken']=$content->access_token;
                    $wxtoken['tokentime']=time();
                    $channelWxModel->where(array('channelid'=>$channelid))->save($wxtoken);
                    return $content->access_token;
                }else{
                    return $wxinfo['atoken'];
                }
		}
	}
	
	
	
	 /**
     * 修改模版信息
     */

    public function tplEdit()
    {
        $id=I('id');
        $tplModel=M('distribution_channel_tplinfo');
        if(IS_POST){
            $tpldata=array();
            $tplpost=(I('post.'));
            foreach ($tplpost as $k=>$v){
                if (is_array($v)){
                    $tpldata[$v[0]]['value']=$v[1];
                    $tpldata[$v[0]]['color']=$v[2];
                }
            }
            $tpldata=json_encode($tpldata);
            $tpl['channelid']=$tplpost['channelid'];
            $tpl['template_id']=$tplpost['template_id'];
            $tpl['url']=$tplpost['url'];
            $tpl['title']=$tplpost['title'];
            $tpl['tpltitle']=$tplpost['tpltitle'];
            $tpl['sendtime']= strtotime($tplpost['sendtime']);
            $tpl['data']=$tpldata;
            $res=$tplModel->where('id = '.$tplpost['id'])->save($tpl);
            if($res!==false){
                $this->success('模版消息保存成功!',U('Channel/tplList'));
                exit;
            }else{
                $this->error('模版消息保存失败!'.$tplModel->getError());
                exit;
            }

        }
        $tpl=$tplModel->find($id);
        $this->assign('tpldata',$tpl);
        $this->display();

    }

	
	

    /**
     * 删除模版消息
     */

    public function tplDel()
    {
        $id=I('id');
        $tplModel=M('distribution_channel_tplinfo');
        $res=$tplModel->delete($id);
        if($res!==false){
            $this->success('删除成功');
        }else{
            $this->error('删除失败');
        }

    }
	
	
	 /**
     * 关键词自动回复表
     */
    public function keywordList()
    {
        $keywordModel=M('distribution_wx_keyword');
        $where=array('channelid'=>cookie('channelid'));

        /************************************* 翻页 ****************************************/
        $count = $keywordModel->where($where)->count();
        $page = new \Think\Page($count, 15);
        // 配置翻页的样式
        $page->setConfig('prev', '上一页');
        $page->setConfig('next', '下一页');
        $page->setConfig('first', '首页');
        $page->setConfig('last', '尾页');
        $showpage = $page->show();
        /************************************** 取数据 ******************************************/
        //var_dump($page->firstRow.','.$page->listRows);exit;
        $keywordList= $keywordModel->where($where)->limit($page->firstRow.','.$page->listRows)->select();
        $this->assign('page',$showpage);
        $this->assign('keywordList',$keywordList);
        $this->display();
    }

    /**
     * 添加关键词
     */

    public function keywordAdd()
    {

        $keywordModel=M('distribution_wx_keyword');
        if(IS_POST){
            //添加关键字渠道
            $_POST['channelid']=cookie('channelid');
            //添加相应公众号id
            if(cookie('pid')==0){
                $_POST['fromid']=cookie('channelid');
            }else{
                $_POST['fromid']=cookie('pid');
            }

            if(!I('title')){
                $_POST['title']='点击 查看全文 ,继续阅读精彩章节';
            }

            if(!I('content')){
                $_POST['content']='点击 查看全文 ,继续阅读精彩章节';
            }

            $_POST['addtime']=time();

            //如果有已存在该关键词退出
            $where=array('fromid'=>$_POST['fromid'],'keyword'=>I('keyword'));
            $data=$keywordModel->field('id')->where($where)->find();

            if($data){
                $this->error('该关键词已被使用!换一个吧!');
                exit;
            }

            $res=$keywordModel->add(I('post.'));
            if($res){
                $this->success('关键词添加成功',U('keywordList'));
                exit;
            }else{
                $this->error('关键词添加失败'.$keywordModel->getError());
                exit;
            }
        }
        $this->display();
    }

    /*
     * 修改关键字
     */
    public function keywordEdit()
    {
        $id=I('id');
        $keywordModel=M('distribution_wx_keyword');
        if(IS_POST){
            //如果有已存在该关键词退出
            $where=array('fromid'=>$_POST['fromid'],'keyword'=>I('keyword'),'id'=>array('neq',$id));
            $data=$keywordModel->field('id')->where($where)->find();
            if($data){
                $this->error('该关键词已被使用!换一个吧!');
                exit;
            }

            $res=$keywordModel->where(array('id'=>$id))->save(I('post.'));

            if($res!==false){
                $this->success('关键词修改成功',U('keywordList'));
                exit;
            }else{
                $this->error('关键词修改失败'.$keywordModel->getError());
                exit;
            }

        }
        $keyword=$keywordModel->find($id);
        $this->assign('keyword',$keyword);

        $this->display();

    }


    /**
     * 删除关键词
     */
    public function keywordDel()
    {
        $id=I('id');
        $keywordModel=M('distribution_wx_keyword');
        $res=$keywordModel->delete($id);
        if($res!==false){
            $this->success('删除成功');
        }else{
            $this->error('删除失败');
        }

    }
	
	
	/**
     * 检测关键词能不能使用
     */
    public function checkKeyword()
    {
        $keywordModel=M('distribution_wx_keyword');

        if(cookie('pid')==0){
            $fromid=cookie('channelid');
        }else{
            $fromid=cookie('pid');
        }
        //如果有已存在该关键词退出
        $where=array('fromid'=>$fromid,'keyword'=>I('keyword'));
		
		if(I('id')){
            $where['id']=array('neq',I('id'));
        }
        $data=$keywordModel->field('id')->where($where)->find();
        if($data){
            $this->error('该关键词已被使用!换一个吧!');
            exit;
        }else{
            $this->success('恭喜这个关键词可以使用!');
        }


    }
    
    /****更新充值笔数****/
	public function uppayment(){
		$data=M('distribution_pay_paylog')
            ->field('count(money) as count,channelid,buytime')
            ->where(array('payflag'=>1))
            ->group('channelid,FROM_UNIXTIME(buytime,"%Y-%m-%d")')
            ->order('buytime DESC')
           
            ->select();
            $payment = M('distribution_payment');
            foreach($data as $k=>$v){
            	$stime = date('Y-m-d',$v['buytime']);
            	$dat['paycount'] = $v['count'];
            	$res = $payment->where(array('asktime'=>$stime,'channelid'=>$v['channelid']))->save($dat);
            }
            //var_dump($data);
	}

    /****根据时间获取结算额****/

    public function getTimePayment($channelidArr,$dailiname,$starttime,$endtime){
    	if(!$starttime&&$endtime){
				$starttime = strtotime(date('Y-m-d',time()))-24*60*60;
				$where['paydate'] = array('BETWEEN',"{$starttime},{$endtime}");
			}

			if(!$endtime&&$starttime){
				$endtime = strtotime(date('Y-m-d',time()))-1;
				$where['paydate'] = array('BETWEEN',"{$starttime},{$endtime}");
			}
			if($endtime&&$starttime){
				$starttime = strtotime("{$starttime}");
				$endtime = strtotime("{$endtime}");
				$where['paydate'] = array('BETWEEN',"{$starttime},{$endtime}");
			}

			if(!$starttime&&!$endtime){
				$starttime = strtotime(date('Y-m-d',time()))-24*60*60;
				$endtime = strtotime(date('Y-m-d',time()))-1;
				$where['paydate'] = $starttime;
			}
			/*if(!$channelid){
				$channelid = cookie('channelid');
			}*/
			if(!empty($dailiname)){
				$where['channelid']=$dailiname;
			}else{
				

	            $where['channelid']=array('IN',$channelidArr);
        	}
        	//充值总额
            $where['status'] = 2;
            if(cookie('permissions')==1){
            	$where['isall']=1;
            }
            
            $data = M('distribution_payment')
            		->field('sum(askmoney) as sumaskmoney,sum(paymoney) as sumpaymoney,sum(paycount) as paycount')
            		->where($where)
            		->select();
            	//	echo M()->getLastSql();
            $data = $data[0];
            $data['sumpaymoney'] = round($data['sumpaymoney'],2);
            //var_dump($data);
            //$data['profit'] = $data['sumaskmoney']-$data['sumpaymoney'];
            return $data;
    }
	
	/***
	*获取下级结算信息
	**/
	public function getNextRemainMoney(){
		if(cookie('uid')>0){
			if(cookie('permissions')==0&&cookie('cpid')==0){
			$channelid = cookie('channelid');
			$channelids=M('distribution_channels')->field('uid,channelid')
                ->where(array('pid'=>$channelid))
                ->select();
            
            }elseif(cookie('permissions')==1){
            	$channelids=M('distribution_channels')->field('uid,channelid')
                ->where(array('pid'=>0))
                ->select();
            }
            $channelidArr =array();    
            foreach($channelids as $key=>$val){
                $channelname = M('system_users')->field('uname')->where(array('uid'=>$val['uid']))->find();
                $channelArr[$key]['channelid']=$val['channelid'];
                $channelArr[$key]['uname']=$channelname['uname'];
                $channelidArr[]=$val['channelid'];
            }
             
            //var_dump($channelidArr);exit;
             
			if(IS_POST){
			//$channelid = I('channelid');
			$starttime = I('starttime');
			$endtime = I('endtime');
			$dailiname = I('dailiname');
			
			$data = $this->getTimePayment($channelidArr,$dailiname,$starttime,$endtime);
            //$data['profitrate'] = round(($data['profit']/$data['sumaskmoney'])*100,2)."%";

            $this->ajaxReturn($data);
            }else{
				if(!$starttime&&!$endtimed){
					$starttime=strtotime(date('Y-m-d'),time())-24*60*60;
					$endtime=strtotime(date('Y-m-d'),time())-1;
				}
				//$starttime=date('Y-m-d',time()-24*60*60);
				//$endtime=date('Y-m-d',time()-24*60*60);
				$data = $this->getTimePayment($channelidArr,'',$starttime,$endtime);
				//var_dump($data);
				$iswhen =1;
			}

            //var_dump($data);exit;
            $startime = date('Y-m-d',$starttime);
            $entime = date('Y-m-d',$endtime);

			$this->assign('data',$data);
			$this->assign('iswhen',$iswhen);
			$this->assign('starttime',$startime);
			$this->assign('endtime',$entime);
            $this->assign('channelArr',$channelArr);		
			$this->display();
		}
	}



	
	/***
	*ajax获取下级结算信息
	**/
	public function ajaxGetNextRemainMoney(){
		
		if(cookie('uid')>0){
			$channelid = cookie('channelid');
			if(cookie('permissions')==1){
				$channelid=1;
			}
			$issum=I('get.issum');
			$starttime = I('post.starttime');
			$endtime = I('post.endtime');
			$dailiname = I('post.dailiname');
			$isoverpay = I('post.isoverpay');
			$iswhen = I('post.iswhen');
			//echo $isoverpay;
			if(!$starttime&&!$endtimed){
				$starttime=strtotime(date('Y-m-d'),time())-24*60*60;
			}
			//var_dump($starttime);
			if($channelid){	
				//$channelInfo = M('distribution_channels')->where(array('pid'=>$channelid))->select();
				$channelModel=D('Channel');
				//var_dump($channelInfo);exit;
					if($isoverpay==''){
						$isoverpay=0;
					}

					if($iswhen==''){
						$iswhen=1;
					}
						if(cookie('permissions')==1){
							$ischannel=0;
						}else{
							$ischannel=1;
						}
						$data = $channelModel->getNextMoney($channelid,$ischannel,$issum,15,$starttime,$endtime,$dailiname,$isoverpay,$iswhen);
						//var_dump($data);exit;
						
						foreach ($data['data'] as $k=>$v){
							$data['data'][$k]['channelinfo'] = $channelModel->getChannelinfo($data['data'][$k]['channelid']);
							$userInfo = $this->getUname($data['data'][$k]['channelinfo']['uid']);
	            			$data['data'][$k]['channelinfo']['uname'] = $userInfo['uname'];
			               
			            }
			            
					}

					//var_dump($data);exit;
					if($iswhen==1){
						$iswhen=1;
					}elseif($iswhen==2){
						$iswhen=2;
					}elseif($iswhen==3){
						$iswhen=3;
					}elseif($iswhen==4){
						$iswhen=4;
					}elseif($iswhen==5){
						$iswhen=5;
					}

					if($isoverpay==2){
						$overpay = 2;
					}elseif($isoverpay==0){
						$overpay = 0;
					}
					$startime = date('Y-m-d',$starttime);
					$this->assign('starttime',$startime);
					$this->assign('endtime',$endtime);

					$this->assign('iswhen',$iswhen);
					$this->assign('isoverpay',$overpay);
					$this->assign('channelid',$channelid);
					$this->assign('page',$data['page']);
					$this->assign('issum',$issum);
					$this->assign('data',$data['data']);
					//var_dump($data['data']);
				$this->display();
		}
		
	}
	
	
    /*
     * 渠道待结算信息
     * */
    public function remainMoney(){
        $channelid=I('channelid');
        if(!empty($channelid)){
            $issum=I('issum');
            $channelModel=D('Channel');

            if(cookie('permissions') == 1){
                $data=$channelModel->getRemainMoney($channelid,0,$issum);
            }else{
                $data=$channelModel->getRemainMoney($channelid,1,$issum);
                //var_dump($data);exit;
                $this->assign('ischannel',1);
            }

            $channelinfo=$channelModel->getChannelinfo($channelid);
            
            $userInfo = $this->getUname($channelinfo['uid']);
            $channelinfo['uname'] = $userInfo['uname'];
            foreach ($data['data'] as $k=>$v){
                $time=$v['buytime'];
                $time=date('Y-m-d',$time);
                $where=array('asktime'=>$time,'channelid'=>$channelid);
				if(cookie('permissions') == 1){
					$where=array('asktime'=>$time,'channelid'=>$channelid,'isall'=>1);
				}
                $status=M('distribution_payment')
                    ->field('status')
                    ->where($where)
                    ->find();
                $data['data'][$k]['status']=$status['status'];
            }
            /*if(cookie('cpid')==0){
            	$datas = $this->getNextRemainMoney($channelid);
            	foreach($datas as $kk=>$vv){
            		if(empty($vv['data'])){
            			unset($datas[$kk]);
            		}
            	}
            	$this->assign('datas',$datas);
            	//var_dump($datas);exit;
            }*/

            $this->assign('data',$data['data']);
            $this->assign('page',$data['page']);
            $this->assign('channelinfo',$channelinfo);
            $this->assign('channelid',$channelid);
            $this->assign('issum',$issum);

            /*渠道财务信息*/
            $bankInfo=$channelModel->getChannelBankinfo($channelid);
            $bankInfo['uname'] = $userInfo['uname'];			
            $this->assign('bankInfo',$bankInfo);

        }
        $this->display();
    }
    //订单详情
    public function paymentInfo(){
        header('content-type:text/html;charset=utf-8');
        $time=I('time');
        $channelid=I('channelid');
        $channelModel=D('Channel');
        $datas=$channelModel->getPaymentInfo($time,$channelid);
        $data=array();
        foreach($datas as $val){
        	$uname = $this->getUname($val['uid']);
        	$val['uname'] = $uname['uname'];
        	$data[] = $val;
        }
        //dump($data);exit();
        $this->assign('data',$data);
        $this->display();
    }


    /**
     * 添加推广平台
     */
    public function addPt()
    {
        //判断有post数据就添加没有显示页面
        if(IS_POST){
            if(!I('post.ptname')){
                $this->error('渠道名称不能为空');exit;
            }
            $channelmodel=D('Channel');
            $res=$channelmodel->addPt();
            if($res){
                $this->success('渠道添加成功!',U('ptList'));
                exit;
            }else{
                $this->error('渠道添加失败'.$channelmodel->getError());exit;
            }



        }
        $this->display();
    }


    /**
     * 添加平台
     */
    public function editPt()
    {
        $ptid=I('id');
        $cost=I('ptcost')+0;
        $oldcost=I('oldcost')+0;
        $channelid=I('channelid');

        $ptModel=M('distribution_channel_pt');
        $channelModel=D('Channel');


        if(IS_POST){
            if(empty($ptid)){
               $this->error('为获取到渠道id');exit;
            }
            $res=$ptModel->where('ptid='.$ptid)->save(I('post.'));
            if($res===false){
                $this->error('编辑信息失败'.$ptModel->getError());exit;
            }else{
                //修改成功后更新渠道成本
                if($cost!=$oldcost){
                    $change=$cost-$oldcost;
                    $channelModel->where('channelid='.$channelid)->setInc('cost',$change);
                }

                $this->success('修改信息成功',U('ptList'));exit;
            }


        }

        $pt=$ptModel->find($ptid);
        //var_dump($pt);exit;

        $this->assign('pt',$pt);
        $this->display();

    }

    /**
     * 推广平台列表
     */
    public function ptList()
    {
		$channelid=I('id');
		if(empty($channelid)){
			$channelid=cookie('channelid');
		}
		$this->assign('channelid',$channelid);
        $this->display();
    }

    /**
     * ajax返回推广平台列表
     */

    public function ajaxPtList()
    {
		$channelid=I('channelid');
		if(empty($channelid)){
			$channelid=cookie('channelid');
		}
        $channelModel=D('Channel');
        $data=$channelModel->getPtList($channelid);
        $this->assign('ptlist',$data['ptlist']);
        $this->assign('page',$data['page']);
        $this->display();


    }
	/**
     * 常用链接
     */
    public function commonUrl(){
        $this->assign('channelid',cookie('channelid'));
        $this->display();
    }
	
	/**
     * 统计渠道数据
     */
    public function dataStatisticsByChannelid()
    {
        $channelid=I('id');
        $channelModel=D('Channel');
        $payModel=D('Pay');

        $dataRemain=$channelModel->getRemainMoney($channelid,1);
        $channelInfo=$channelModel->field('proportion,channelname')->where(array('channelid'=>$channelid))->find();

        $dayPayInfo=$payModel->dayPayInfo($channelid,1);  /*渠道今日充值统计*/

        $pay_file='./paylogInfo/statistics_'.$channelid.'.txt';
        $dataPay=file_get_contents($pay_file);
        $today=date("Ymd",time());
        $dataPayArr=json_decode($dataPay,true);
        if($dataPayArr['today']==$today){
            $payInfo=$dataPayArr;
        }else{
            $payInfo=$payModel->sumPayInfo($channelid,1);
        }

        
            
        //渠道用户数据统计
        $userModel=D('User');
        $daysign=$userModel->getdaySignCount($channelid);
        $this->assign('daysign',$daysign);

        $dayUserInfo=$userModel->getDayUserInfo($channelid,1);   /*今日新增用户*/

        $user_file='./userInfo/statistics_'.$channelid.'.txt';

        $dataUser=file_get_contents($user_file);
        $dataUserArr=json_decode($dataUser,true);
        if($dataUserArr['today']==$today){
            $userInfo=$dataUserArr;
        }else{
            $userInfo=$userModel->getUserInfo($channelid,1);
        }

        $this->assign('dayUserInfo',$dayUserInfo);
        $this->assign('userInfo',$userInfo);  

        $this->assign('data',$dataRemain['data']);
        $this->assign('channelInfo',$channelInfo);
        $this->assign('dayPayInfo',$dayPayInfo);
        $this->assign('payInfo',$payInfo);
        $this->assign('channelid',$channelid);

        $this->display();
    }
	
	
    /**
     * 微信验证文件上传
     */

    public function wxCheckUpload()
    {
        $upload = new \Think\Upload(array(
            'rootPath' => C('BOOK_DIR'),
            'maxSize' => 1024*1024,
            'exts' => 'txt',
            'autoSub'=>false,
            'saveName'=>substr($_FILES['checkFile']['name'],0,strpos('.')),
        ));// 实例化上传类

        if(substr($_FILES['checkFile']['name'],0,3)!='MP_'){
            $this->ajaxReturn(array('error'=>'1','msg'=>'上传的不是微信验证文件'));
        }

        $info   =   $upload->upload();

        if($info){
            $this->ajaxReturn(array('error'=>'0','msg'=>$upload->getError()));
        }else{
            $this->ajaxReturn(array('error'=>'1','msg'=>$upload->getError()));
        }
    }


}
